name: CI/CD para Atualização de API Dog

on:
  push:
    branches:
      - main  # Ou a branch que você desejar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instalar dependências
      - name: Instalar dependências
        run: npm install

      # 4. Build do projeto
      - name: Build do Projeto
        run: npm run build

      # 5. Gerar o arquivo Swagger
      - name: Gerar arquivo Swagger
        run: npm run swagger:generate  # Certifique-se de ter o script configurado no package.json

    # 6. Enviar documentação para o API Dog
      - name: Atualizar documentação no Apidog
        env:
          APIDOG_API_URL: ${{ secrets.APIDOG_API_URL }}
          APIDOG_TOKEN: ${{ secrets.APIDOG_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          API_VERSION: ${{ secrets.API_VERSION }}
        run: |
          curl --request POST \
            --url "$APIDOG_API_URL/v1/projects/$PROJECT_ID/import-openapi" \
            --header "Authorization: Bearer $APIDOG_TOKEN" \
            --header "X-Apidog-Api-Version: $API_VERSION" \
            --header "Content-Type: application/json" \
            --data @path/to/swagger-spec.json
